"resource/ui/replaybrowser/thumbnailcollection.res"
{
	"ThumbnailCollection"
	{
		"ControlName"			"Panel"
		"fieldName"				"ThumbnailCollection"
		"wide"					"f0"
		"tall"					"180"
		"autoResize"			"0"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"settitlebarvisible"	"1"
	}
	"RenderAllButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"RenderAllButton"
		"wide"			"75"
		"tall"			"15"
		"zpos"			"5"
		"visible"		"0"
		"enabled"		"1"
		"font"			"HudFontSmallestBold"
		"textAlignment"	"center"
		"text"			"#Replay_RenderAll"
		"Command"		"render_queued_replays"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		
		"defaultBgColor_override"	"ButtonBG"
		"armedBgColor_override"		"AntsHUDDeepSkyBlue"
		"depressedBgColor_override"	"ButtonBG"
		
		"defaultFgColor_override"	"AntsHUDWhite"
		"armedFgColor_override" 	"AntsHUDWhite"
		"depressedFgColor_override" "AntsHUDGray"
		
		"border_default"			"NoBorder"
		"border_armed"				"NoBorder"
		
	}
	"TitleLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"TitleLabel"
		"font"			"HudFontMediumSmallBold"
		"labelText"		"%titleandcount%"
		"textAlignment"	"west"
		"zpos"			"2"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"wide"			"f0"
		"fgcolor"		"AntsHUDWhite"
	}
	"DateLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"DateLabel"
		"font"			"HudFontSmallestBold"
		"textAlignment"	"west"
		"zpos"			"2"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"wide"			"f0"
		"fgcolor_override" "AntsHUDGray"
	}
	"WarningLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"WarningLabel"
		"font"			"HudFontSmallest"
		"textAlignment"	"west"
		"zpos"			"1"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"fgcolor_override" "AntsHUDGray"
		"wrap"			"1"
	}
	"Line"
	{
		"ControlName"	"Panel"
		"FieldName"		"Line"
		"zpos"			"2"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"bgcolor_override" "0 0 0 0"
	}
	"CaratLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"CaratLabel"
		"font"			"HudFontSmallestBold"
		"textAlignment"	"west"
		"labelText"		""
		"auto_wide_tocontents" "1"
		"tall"			"0"
		"zpos"			"2"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"0"
		"wide"			"0"
		"fgcolor_override" "0 0 0 0"
	}
	"UnconvertedBg"
	{
		"ControlName"	"Panel"
		"fieldName"		"UnconvertedBg"
		"zpos"			"1"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"bgcolor_override" "BGAnyLight"
	}
	"NoReplayItemsLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"NoReplayItemsLabel"
		"font"			"AvenirBla12"
		"wide"			"400"
		"tall"			"40"
		"zpos"			"5"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"centerwrap"	"1"
		"fgcolor_override"	"AntsHUDGray"
	}
	"ShowPrevButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"ShowPrevButton"
		"xpos"			"0"
		"ypos"			"0"
		"zpos"			"100"
		"wide"			"100"
		"tall"			"12"
		"autoResize"	"0"
		"pinCorner"		"3"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"%prevbuttontext%"
		"font"			"ItemFontNameSmall"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"1"
		"Command"		"show_prev"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"paintbackground"	"1"
		"defaultBgColor_override"	"ButtonBG"
		"armedBgColor_override"		"AntsHUDDeepSkyBlue"
		"depressedBgColor_override"	"AntsHUDDeepSkyBlue"
		"defaultFgColor_override"	"AntsHUDWhite"
		"armedFgColor_override" 	"AntsHUDWhite"
		"depressedFgColor_override" "AntsHUDWhite"
		"border_default"			"NoBorder"
		"border_armed"				"NoBorder"
	}
	"ShowNextButton"
	{
		"ControlName"	"CExButton"
		"fieldName"		"ShowNextButton"
		"xpos"			"100"
		"ypos"			"20"
		"zpos"			"100"
		"wide"			"100"
		"tall"			"12"
		"autoResize"	"0"
		"pinCorner"		"3"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"	"0"
		"labelText"		"%nextbuttontext%"
		"font"			"ItemFontNameSmall"
		"textAlignment"	"center"
		"dulltext"		"0"
		"brighttext"	"0"
		"default"		"1"
		"Command"		"show_next"
		"sound_depressed"	"UI/buttonclick.wav"
		"sound_released"	"UI/buttonclickrelease.wav"
		"paintbackground"	"1"
		"defaultBgColor_override"	"ButtonBG"
		"armedBgColor_override"		"AntsHUDDeepSkyBlue"
		"depressedBgColor_override"	"AntsHUDDeepSkyBlue"
		"defaultFgColor_override"	"AntsHUDWhite"
		"armedFgColor_override" 	"AntsHUDWhite"
		"depressedFgColor_override" "AntsHUDWhite"
		"border_default"			"NoBorder"
		"border_armed"				"NoBorder"
	}
}